### ISSUE TITLE
RODC

### ISSUE THREAD

**Issue by RobertTs80** [joelmleo/Public#1]
Hi Joel,

just a FYI;
RODC records can not be located in certain Folders e.g. _ldap , _gc, ... which is perfect fine and by design of RODCs. maybe you like to consider this in upcoming versions.
thanks and regards,
Robert

*i found your script very helpful and really good ! :)

**Comment by joelmleo** [comment]
Aloha RobertTs80!

Thanks for the feedback. I've been heads-down on a number of internal projects, but will definitely take your feedback in to consideration the next time I review the script. In the mean time, feel free to customize it to your needs or fork it and fix it as you see fit.

Thanks again - have a great $workUnit ;)
